# Generated by Django 4.2.4 on 2024-01-11 22:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "name",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("slug", models.SlugField(unique=True)),
                ("full_name", models.CharField(max_length=250, unique=True)),
                ("market", models.CharField(max_length=250)),
                (
                    "report_date",
                    models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
                ),
                ("report_status", models.CharField(default="final", max_length=25)),
                ("offset", models.IntegerField(default=0)),
                ("mmn_url", models.CharField(max_length=500)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("head1", models.IntegerField(default=0, verbose_name="hd 700")),
                ("weight1", models.FloatField(default=0, verbose_name="wgt 700-749")),
                ("price1", models.FloatField(default=0, verbose_name="px 700-749")),
                ("head2", models.IntegerField(default=0, verbose_name="hd 750")),
                ("weight2", models.FloatField(default=0, verbose_name="wgt 750-799")),
                ("price2", models.FloatField(default=0, verbose_name="wgt 750-799")),
                ("head3", models.IntegerField(default=0, verbose_name="hd 800")),
                ("weight3", models.FloatField(default=0, verbose_name="wgt 800-849")),
                ("price3", models.FloatField(default=0, verbose_name="wgt 800-849")),
                ("head4", models.IntegerField(default=0, verbose_name="hd 850")),
                ("weight4", models.FloatField(default=0, verbose_name="wgt 850-899")),
                ("price4", models.FloatField(default=0, verbose_name="px 850-899")),
                ("head5", models.IntegerField(default=0, verbose_name="hd")),
                ("weight5", models.FloatField(default=0, verbose_name="wgt")),
                ("price5", models.FloatField(default=0, verbose_name="px")),
                ("final_ind", models.CharField(default="final", max_length=25)),
                ("region", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="api.auction",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
