# Generated by Django 4.2.4 on 2023-08-31 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("full_name", models.CharField(max_length=250, unique=True)),
                ("market", models.CharField(max_length=250)),
                (
                    "last_final_sale_date",
                    models.DateField(default=datetime.datetime(2023, 1, 1, 0, 0)),
                ),
                ("offset", models.IntegerField(default=0)),
                ("mmn_url", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("head1", models.IntegerField(default=0)),
                ("weight1", models.FloatField(default=0)),
                ("price1", models.FloatField(default=0)),
                ("head2", models.IntegerField(default=0)),
                ("weight2", models.FloatField(default=0)),
                ("price2", models.FloatField(default=0)),
                ("head3", models.IntegerField(default=0)),
                ("weight3", models.FloatField(default=0)),
                ("price3", models.FloatField(default=0)),
                ("head4", models.IntegerField(default=0)),
                ("weight4", models.FloatField(default=0)),
                ("price4", models.FloatField(default=0)),
                ("head5", models.IntegerField(default=0)),
                ("weight5", models.FloatField(default=0)),
                ("price5", models.FloatField(default=0)),
                ("final_ind", models.CharField(default="final", max_length=25)),
                ("region", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="api.auction",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
