# Generated by Django 4.2.4 on 2023-08-17 07:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Auction",
            fields=[
                ("slug", models.SlugField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250, unique=True)),
                ("display_name", models.CharField(max_length=250, unique=True)),
                ("market", models.CharField(max_length=250, unique=True)),
                ("last_updated", models.DateTimeField(default=datetime.datetime.now)),
                ("offset", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("head1", models.IntegerField(default=0)),
                ("weight1", models.FloatField(default=0)),
                ("price1", models.FloatField(default=0)),
                ("head2", models.IntegerField(default=0)),
                ("weight2", models.FloatField(default=0)),
                ("price2", models.FloatField(default=0)),
                ("head3", models.IntegerField(default=0)),
                ("weight3", models.FloatField(default=0)),
                ("price3", models.FloatField(default=0)),
                ("head4", models.IntegerField(default=0)),
                ("weight4", models.FloatField(default=0)),
                ("price4", models.FloatField(default=0)),
                ("head5", models.IntegerField(default=0)),
                ("weight5", models.FloatField(default=0)),
                ("price5", models.FloatField(default=0)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="api.auction",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
