# Generated by Django 4.2.4 on 2023-09-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="mmn_url",
            field=models.CharField(max_length=500),
        ),
    ]
