# Generated by Django 4.2.4 on 2023-09-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_auction_mmn_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="region",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
