# Generated by Django 4.2.4 on 2023-08-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_sale_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="market",
            field=models.CharField(max_length=250),
        ),
    ]
