# Generated by Django 4.2.4 on 2023-08-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_auction_market"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="final_ind",
            field=models.CharField(default="final", max_length=25),
        ),
        migrations.AddField(
            model_name="sale",
            name="region",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
