# Generated by Django 4.2.4 on 2023-08-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_sale_final_ind_sale_region"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auction",
            old_name="last_updated",
            new_name="last_final_sale_date",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="display_name",
        ),
        migrations.AddField(
            model_name="auction",
            name="full_name",
            field=models.CharField(default="name", max_length=250, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auction",
            name="mmn_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auction",
            name="name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
