# Generated by Django 4.2.4 on 2023-08-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_last_updated_auction_last_final_sale_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="mmn_url",
            field=models.CharField(default="default", max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auction",
            name="name",
            field=models.CharField(default="default", max_length=250),
            preserve_default=False,
        ),
    ]
